require:
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Metrics/AbcSize:
  Exclude:
    - app/controllers/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 12

Naming/VariableNumber:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Performance/BlockGivenWithExplicitBlock:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 5

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/UnlessLogicalOperators:
  EnforcedStyle: forbid_logical_operators

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false
